title: Maliketh
description: A flexible, easy to use C2 framework that can be customized to fit the needs of the operator
theme: just-the-docs
color_scheme: dark_custom
logo: "/data/maliketh_logo.png"
favicon_ico: "/data/favicon.ico"
ga_tracking: G-FZN282X13R

url: https://malikethframework.com

aux_links:
  Maliketh on GitHub: https://github.com/cbrnrd/maliketh

heading_anchors: true

footer_content: "Copyright &copy; 2023 Carter Brainerd. All rights reserved."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/cbrnrd/maliketh-site"

plugins:
  - jekyll-seo-tag

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

enable_code_copy_button: true
enable_search: true

callouts:
  warning:
    title: Warning!
    color: red
  note:
    title: Note
    color: yellow
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: blue

collections:
  home_index:
    output: true
    permalink: "/:collection/:path/"
  
just_the_docs:
  collections:
    home_index:
      name: Home
      nav_exclude: true